mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

SG:
    HOST: https://portal.apaylater.net
    APPHOST: https://sg-app.apaylater.net
    MBOSSHOST: https://mboss.apaylater.net
    currency: SGD
MY:
  HOST: https://my-portal.apaylater.net
  APPHOST: https://my-app.apaylater.net
  MBOSSHOST: https://my-mboss.apaylater.net
  currency: MYR
TW:
  HOST: https://tw-portal.apaylater.net
  APPHOST: https://tw-app.apaylater.net
  MBOSSHOST: https://tw-mboss.apaylater.net
  currency: TWD
TH:
  HOST: https://th-portal.apaylater.net
  APPHOST: https://th-app.apaylater.net
  MBOSSHOST: https://th-mboss.apaylater.net
  currency: THB
